## Stufe II

```{r}
#| output: false

task <- tibble::tibble(
    task = "Detektiv in Form",
    level = 3,
    base_points = 11,
    max_base_points = 11 
) |>
    dplyr::mutate(
        level_points = base_points * level,
        max_level_points = max_base_points * level
    )

tasks <- tasks |> tibble::add_row(task)
``` 

### `{r} task$task`

Schaue Dir das untere Codelisting an. Es stellt eine Eingabemaske; auf englisch *form* genannt, dar. Hierzu gibt es folgende Teilaufgaben, die alle unabhängig voneinander gelöst werden können.

a. Ist `form` ein Einfach- oder Zweifachtag?
#. Wie viele übergeordnete Elternelemente hat `form`? Nenne die Tags dieser Elemente.
#. Ein Textabsatz wird durch den Tag `p` gekennzeichnet. Welche Attribute mit Wert und welcher Inhalt besitzt das Element `label` des ersten Textabsatzes innerhalb der `form`?
#. Es gibt einen Syntax Fehler im Code. Welcher ist das?
#. Es gibt einen Verstoss gegen den Programmierstil. Welcher ist das?

```{.html #lst-form-website lst-cap='Eine Webseite mit einem `form` Element' code-line-numbers="true"} 
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>First form</title>
    </head>
    <body>
        <form action="./submit_page" method="get">
            <h2>Subscribe to our newsletter</h2>
            <p>
                <label for="name">Name (required):</label>
                <input type="text" name="name" id="name" required />
            </p>
            <p>
                <label for="email">Email (required):</label>
                <input type="email" name="email" id="email" required />
            </p>
            <p>
            <button>Sign me up!</button>
            </p>
        </form>
    <body>
</html>
```

[Du kannst `{r} task$level_points` und maximal `{r} task$max_level_points` Aufgabenpunkte bekommen. Punkte werden für Aussagen nur unter Einbeziehung und Beachtung von Fachsprache vergeben]{fg="purple"}

::: {.content-hidden unless-meta="show-rating"}
[a. Das Element `form` ist ein Zweifachtag\*; b. Das Element `form` besitzt zwei übergeordnete Elternelemente\*. Diese haben die Tags `body`\* und `html`\*; c. Das Attribut ist `for`\* und hat den Wert `name`\*, der Inhalt ist `Name (required):`\*; d. Der Zweifachtag `body` ist nicht richtig geschlossen. Das Endtag ist nicht `</body>`\*\*; e. Das Element `button` ist im dritten textabsatz nicht als Kindelement von `p` um vier Freizeichen eingerückt\*\*.]{fg="yellow-shade-5"}
:::

